"""错误码目录。"""


class ErrorCodeCatalog:
    """统一错误码目录。"""

    REQUEST_INVALID = "REQUEST_INVALID"
    RETRIEVAL_EMPTY = "RETRIEVAL_EMPTY"
    SQL_GENERATION_FAILED = "SQL_GENERATION_FAILED"
    SQL_EXECUTION_FAILED = "SQL_EXECUTION_FAILED"
    MEMORY_WRITE_FAILED = "MEMORY_WRITE_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    SYSTEM_UNAVAILABLE = "SYSTEM_UNAVAILABLE"
